[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "optimodel-py"
version = "1.10.3"
authors = [
  { name="Lytix", email="support@lytix.com" },
]
description = "A smart framework for calling models in the most efficient way possible"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "requests==2.31.0",
  "urllib3==2.2.1",
  "aiohttp==3.9.5",
  "optimodel-server==1.10.2",
  "optimodel-types==0.1.2"
]

[project.urls]
Homepage = "https://github.com/Lytix-Labs/optimodel"
Issues = "https://github.com/Lytix-Labs/optimodel/issues"